package edu.ntnu.idi.idatt.navigation;

public enum NavigationTarget {
  INTRO_SCREEN,
  CHARACTER_SELECTION,
  SAL_RULE_SELECTION,
  START_SCREEN,
  SAL_GAME_SCREEN,
  STAR_INTRO,
  STAR_GAME,
  STAR_CHARACTER_SELECTION,
  STAR_LOAD_SCREEN,
  SNL_LOAD_SCREEN,

  MEMORY_RULE_SCREEN,
  MEMORY_GAME_SCREEN,

  PAINT_CANVAS

}
